name: Publish to NPM registry

on:
  release:
    types: [ published ]
  workflow_dispatch:

jobs:
  build-package:
    name: Build and publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

      - name: Setup NodeJS
        uses: actions/setup-node@v2
        with:
          node-version: 14
          cache: 'yarn'
          registry-url: https://registry.npmjs.org/

      - name: Install deps and build (with cache)
        uses: bahmutov/npm-install@v1.4.5
        with:
          install-command: yarn --frozen-lockfile --silent

      - name: Build
        run: yarn build

#      - name: Run tests
#        run: yarn test

      - name: Publish to npmjs registry
        run: yarn publish --access public
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
